import {CONFIG as C} from './config.js';
export class AudioFX{
  constructor(enabled){this.enabled=enabled;this.ctx=null;this.rain=null;}
  unlock(){try{if(!this.ctx){this.ctx=new(window.AudioContext||window.webkitAudioContext)();this.master=this.ctx.createGain();this.master.gain.value=C.audio.master;this.master.connect(this.ctx.destination);}if(this.ctx.state==='suspended')this.ctx.resume();}catch{}}
  setEnabled(value){this.enabled=value;if(!value)this.setRain(false);}
  tone(freq,duration,level,type='sine',delay=0){if(!this.enabled||!this.ctx)return;const at=this.ctx.currentTime+delay,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(freq,at);o.frequency.exponentialRampToValueAtTime(Math.max(30,freq*.6),at+duration);g.gain.setValueAtTime(0,at);g.gain.linearRampToValueAtTime(level,at+.006);g.gain.exponentialRampToValueAtTime(.0001,at+duration);o.connect(g);g.connect(this.master);o.start(at);o.stop(at+duration+.01);}
  noise(duration,level,lowpass=700){if(!this.enabled||!this.ctx)return;const n=this.ctx.sampleRate*duration,b=this.ctx.createBuffer(1,n,this.ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<n;i++)d[i]=(Math.random()*2-1)*(1-i/n);const s=this.ctx.createBufferSource(),f=this.ctx.createBiquadFilter(),g=this.ctx.createGain();s.buffer=b;f.type='lowpass';f.frequency.value=lowpass;g.gain.value=level;s.connect(f);f.connect(g);g.connect(this.master);s.start();}
  play(type){const a=C.audio,f=a.frequencies;if(type==='turn')this.tone(f.turn,.075,a.turn);if(type==='hit'){this.tone(f.hit,.14,a.hit,'triangle');this.noise(.12,.1,1200);}if(type==='death')this.tone(f.death,.5,a.death,'triangle');if(type==='record'){[0,1,2].forEach(i=>this.tone(f.record*2**(i/5),.18,a.record,'sine',i*.1));}if(type==='thunder')this.noise(1.7,a.thunder,240);}
  setRain(on){if(!on||!this.enabled||!this.ctx){if(this.rain){this.rain.stop();this.rain.disconnect();this.rain=null;}return;}if(this.rain)return;const b=this.ctx.createBuffer(1,this.ctx.sampleRate*2,this.ctx.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=Math.random()*2-1;const s=this.ctx.createBufferSource(),g=this.ctx.createGain(),filter=this.ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=1400;s.buffer=b;s.loop=true;g.gain.value=C.audio.rain;s.connect(filter);filter.connect(g);g.connect(this.master);s.start();this.rain=s;}
}
