import {CONFIG as C} from './config.js';import {Engine,multiplier} from './engine.js';import {readSave,writeSave} from './storage.js';import {AudioFX} from './audio.js';import {loadAssets,Renderer} from './renderer.js';import {bindInput} from './input.js';
const $=id=>document.getElementById(id),save=readSave(),audio=new AudioFX(save.sound),game=new Engine();let renderer,draft,mode='loading',countLeft=0,resuming=false,last=performance.now(),menuTime=0,tutorialUntil=0,toastUntil=0;
export function formatTime(t){const tenths=Math.floor((t+1e-8)*10);return `${String(Math.floor(tenths/600)).padStart(2,'0')}:${String(Math.floor(tenths/10)%60).padStart(2,'0')}.${tenths%10}`;}
function persist(){if(!writeSave(save))$('control-caption').textContent='브라우저 저장이 제한되어 기록이 유지되지 않을 수 있습니다.';}
function screen(name){for(const id of ['loading','start','countdown','paused','end'])$(id).hidden=id!==name;mode=name||'playing';$('oops').disabled=mode!=='playing';$('pause').disabled=mode!=='playing';}
function soundLabel(){$('sound').textContent=save.sound?'소리 켬':'소리 끔';$('sound').setAttribute('aria-label',save.sound?'소리 끄기':'소리 켜기');}
function stats(){$('time').textContent=formatTime(game.elapsed);$('best').textContent=formatTime(save.best);$('chip-count').textContent=game.chips;$('chips').replaceChildren(...Array.from({length:C.survival.initialChips},(_,i)=>{const chip=document.createElement('i');chip.className='chip'+(i>=game.chips?' used':'');chip.setAttribute('aria-label',i<game.chips?'활성 블루칩':'소모된 블루칩');return chip;}));$('map-name').textContent=C.maps[game.map].name;$('weather').textContent=game.storm?'폭풍 날씨':'기본 날씨';$('speed').textContent=`낙하 ×${multiplier(game.elapsed).toFixed(2)}`;}
function caption(){$('loadout-caption').textContent=[['helmet','helmets'],['outfit','outfits'],['gun','guns']].map(([k,l])=>C.equipment[l].find(o=>o.id===save.loadout[k]).name).join(' · ');}
function countdown(resume=false){audio.unlock();resuming=resume;countLeft=C.countdown;if(!resume){game.reset();toastUntil=0;$('map-toast').classList.remove('visible');stats();}screen('countdown');$('count-number').textContent=Math.ceil(countLeft);audio.setRain(false);last=performance.now();}
function pause(){if(mode==='playing'||mode==='countdown'){if(mode==='playing')game.pause();screen('paused');audio.setRain(false);$('tutorial').hidden=true;}}
function finish(){const fresh=game.elapsed>save.best;if(fresh){save.best=game.elapsed;persist();audio.play('record');}$('result-time').textContent=formatTime(game.elapsed);$('result-best').textContent=formatTime(save.best);$('record-banner').hidden=!fresh;stats();screen('end');audio.setRain(false);$('tutorial').hidden=true;}
function turn(){if(game.flip()){save.tutorial=true;persist();$('tutorial').hidden=true;}}
$('brand').textContent=C.branding.title;$('credit').textContent=C.branding.credit;$('oops').textContent=C.branding.button;document.title=`${C.branding.title} · ${C.branding.name}`;soundLabel();
$('sound').onclick=()=>{audio.unlock();save.sound=!save.sound;audio.setEnabled(save.sound);soundLabel();persist();audio.setRain(mode==='playing'&&game.storm);};
$('pause').onclick=pause;$('start-button').onclick=()=>countdown();$('retry').onclick=()=>countdown();$('resume').onclick=()=>countdown(game.status==='paused');$('home').onclick=()=>{game.reset();screen('start');caption();stats();};
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();last=performance.now();});window.addEventListener('blur',pause);window.addEventListener('resize',()=>renderer?.resize());
bindInput($('oops'),turn,()=>mode==='playing'&&game.status==='playing',()=>audio.unlock());
function equipmentUI(){const groups=[['helmet','helmets','헬멧'],['outfit','outfits','복장'],['gun','guns','총기']];$('equipment').replaceChildren(...groups.map(([key,list,label])=>{const section=document.createElement('section');section.className='equipment-group';const title=document.createElement('h3');title.textContent=label;const grid=document.createElement('div');grid.className='equipment-grid';for(const item of C.equipment[list]){const btn=document.createElement('button');btn.type='button';btn.className='equip';btn.dataset.key=key;btn.dataset.value=item.id;btn.setAttribute('aria-pressed',String(draft[key]===item.id));const image=document.createElement('img');image.src=item.asset;image.alt='';const name=document.createElement('span');name.textContent=item.name;btn.append(image,name);btn.onclick=()=>{draft[key]=item.id;for(const b of grid.children)b.setAttribute('aria-pressed',String(b.dataset.value===item.id));renderer.preview($('custom-preview'),draft,menuTime);};grid.append(btn);}section.append(title,grid);return section;}));}
$('custom-button').onclick=()=>{if(mode!=='start')return;draft={...save.loadout};equipmentUI();$('custom-dialog').showModal();};
function closeCustom(){$('custom-dialog').close();draft=null;}
$('custom-close').onclick=closeCustom;$('custom-cancel').onclick=closeCustom;$('custom-dialog').addEventListener('cancel',()=>{draft=null;});$('custom-apply').onclick=()=>{save.loadout={...draft};persist();caption();closeCustom();};
function frame(now){let dt=Math.max(0,(now-last)/1000);last=now;
  // Treat a long stalled foreground frame like a background interruption; never fast-forward hazards.
  if(dt> .5&&(mode==='playing'||mode==='countdown')){pause();dt=0;}
  if(mode==='countdown'){countLeft-=dt;$('count-number').textContent=Math.max(1,Math.ceil(countLeft));if(countLeft<=0){if(resuming)game.resume();else game.start();screen(null);if(!save.tutorial){$('tutorial').hidden=false;tutorialUntil=game.elapsed+4;save.tutorial=true;persist();}audio.setRain(game.storm);}}
  else if(mode==='playing'){game.step(dt);for(const e of game.consumeEvents()){audio.play(e.type);if(e.type==='map'){$('map-toast').textContent=`${C.maps[e.index].name}${e.storm?' · 폭풍':''}`;$('map-toast').classList.add('visible');toastUntil=game.elapsed+2;audio.setRain(e.storm);}if(e.type==='death')finish();}if(game.elapsed>tutorialUntil)$('tutorial').hidden=true;stats();}
  if(game.elapsed>toastUntil)$('map-toast').classList.remove('visible');if(mode==='start'||$('custom-dialog').open)menuTime+=dt;
  if(renderer){renderer.draw(game,save.loadout,menuTime);if(mode==='start')renderer.preview($('start-preview'),save.loadout,menuTime);if($('custom-dialog').open)renderer.preview($('custom-preview'),draft||save.loadout,menuTime);}requestAnimationFrame(frame);
}
try{const images=await loadAssets();renderer=new Renderer($('game'),images);game.assetSizes=Object.fromEntries(C.obstacles.map(o=>{const i=images.get(o.asset);return[o.id,{width:i.width,height:i.height}];}));caption();stats();screen('start');last=performance.now();requestAnimationFrame(frame);}catch(e){$('load-message').textContent=`${e.message}. 파일 경로를 확인한 뒤 새로고침해 주세요.`;}
// Opt-in local QA access only; no debug interface in normal play.
if(new URLSearchParams(location.search).get('qa')==='1')window.__OOPS_QA__={game,save,audio,countdown,pause,stats,turn,get mode(){return mode;}};
