import {CONFIG as C} from './config.js';
export async function loadAssets(){const paths=new Set([...C.player.frames,...C.maps.map(x=>x.asset),...C.obstacles.map(x=>x.asset),...Object.values(C.equipment).filter(Array.isArray).flat().map(x=>x.asset),C.assets.crate]);const images=new Map();await Promise.all([...paths].map(path=>new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{images.set(path,img);resolve();};img.onerror=()=>reject(Error(`에셋 로드 실패: ${path}`));img.src=path;})));return images;}
export function drawPlayer(ctx,images,x,y,size,dir,phase,loadout,invincible=false){ctx.save();ctx.translate(x,y);ctx.scale(dir,1);ctx.fillStyle='#101f2660';ctx.beginPath();ctx.ellipse(0,size*.49,size*.34,size*.075,0,0,Math.PI*2);ctx.fill();if(invincible)ctx.globalAlpha=Math.floor(phase*14)%2?.46:1;const img=images.get(C.player.frames[Math.floor(phase*C.player.animationFPS)%C.player.frames.length]);const baseWidth=size*img.width/img.height;ctx.drawImage(img,-baseWidth/2,-size*.5,baseWidth,size);
  for(const [key,list]of [['outfit','outfits'],['helmet','helmets'],['gun','guns']]){const spec=C.equipment[list].find(o=>o.id===loadout[key]);const image=images.get(spec.asset),box=spec.id==='ghillie'?C.equipment.layout.ghillie:C.equipment.layout[key];const maxW=size*box.width,maxH=size*box.height,scale=Math.min(maxW/image.width,maxH/image.height),w=image.width*scale,h=image.height*scale;ctx.drawImage(image,size*box.x-w/2,size*box.y-h/2,w,h);}ctx.restore();}
export class Renderer{
  constructor(canvas,images){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.images=images;this.oldMap=0;this.map=0;this.transitionAt=-5;this.previewCanvases=[];this.resize();}
  resize(){const dpr=Math.min(window.devicePixelRatio||1,2);this.canvas.width=C.world.width*dpr;this.canvas.height=C.world.height*dpr;this.ctx.setTransform(dpr,0,0,dpr,0,0);this.dpr=dpr;}
  preview(canvas,loadout,t){const ctx=canvas.getContext('2d');ctx.clearRect(0,0,canvas.width,canvas.height);drawPlayer(ctx,this.images,canvas.width/2,canvas.height*.49,canvas.height*.72,1,t,loadout);}
  draw(g,loadout,menuTime=0){const ctx=this.ctx,W=C.world.width,H=C.world.height,t=g.status==='ready'?menuTime:g.elapsed;
    if(g.map!==this.map){this.oldMap=this.map;this.map=g.map;this.transitionAt=g.elapsed;}if(g.elapsed===0){this.map=0;this.oldMap=0;this.transitionAt=-5;}
    ctx.clearRect(0,0,W,H);ctx.drawImage(this.images.get(C.maps[this.oldMap].asset),0,0,W,H);ctx.save();ctx.globalAlpha=Math.min(1,(g.elapsed-this.transitionAt)/C.weather.transition);ctx.drawImage(this.images.get(C.maps[g.map].asset),0,0,W,H);ctx.restore();
    ctx.fillStyle='#12263116';ctx.fillRect(0,0,W,H);ctx.fillStyle='#12202a45';ctx.fillRect(0,510,W,66);ctx.strokeStyle='#ffffff30';ctx.setLineDash([6,10]);ctx.beginPath();ctx.moveTo(0,574);ctx.lineTo(W,574);ctx.stroke();ctx.setLineDash([]);
    if(g.storm){ctx.fillStyle=`rgba(8,20,36,${C.weather.dim})`;ctx.fillRect(0,0,W,H);ctx.strokeStyle=`rgba(192,222,243,${C.weather.rainOpacity})`;ctx.lineWidth=1;for(let i=0;i<C.weather.rainCount;i++){const x=(i*83.7-t*37)%W,y=(i*143.9+t*370)%H;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-4,y+16);ctx.stroke();}if(g.lightning>0){ctx.strokeStyle='#c0d4e96a';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(330,0);ctx.lineTo(306,35);ctx.lineTo(319,32);ctx.lineTo(293,68);ctx.stroke();ctx.fillStyle=`rgba(205,226,247,${C.weather.lightningOpacity*g.lightning/.22})`;ctx.fillRect(0,0,W,H);}}
    for(const o of g.obstacles){const image=this.images.get(o.spec.asset);ctx.save();ctx.translate(o.x,o.y);ctx.rotate(-o.angle*.35);ctx.drawImage(image,-o.w/2,-o.h/2,o.w,o.h);ctx.restore();}
    if(g.status==='dead'){const image=this.images.get(C.assets.crate);const w=45,h=45*image.height/image.width;ctx.drawImage(image,g.x-w/2,C.player.y-h/2,w,h);}
    else if(g.status!=='ready')drawPlayer(ctx,this.images,g.x,C.player.y,C.player.size*C.world.unit,g.dir,t,loadout,g.elapsed<g.invincibleUntil);
    if(g.hitFlash>0){ctx.strokeStyle=`rgba(255,142,98,${g.hitFlash/.18})`;ctx.lineWidth=4;ctx.strokeRect(2,2,W-4,H-4);}
  }
}
